version: '3'
services:
  db:
    container_name: odoo16_db
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: always            
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  web:
    container_name: odoo16_web
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo

  pgadmin:
      image: dpage/pgadmin4
      depends_on:
       - db
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8887:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: mucharomtzaka@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 12345678
      volumes:
        - ./pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin: